### ISSUE TITLE
Webpack build plugin

### ISSUE THREAD

**Issue by TheAlexLichter** [HapLifeMan/purifycss-extended#4]
Hey,

first of all: Great job on improving purifycss!
Could you also provide a build plugin for webpack (similar to the [original one](https://github.com/FullHuman/purgecss-webpack-plugin))?

Best regards :)

**Comment by HapLifeMan** [comment]
Hey, thank you! I forked the original `webpack-contrib/purifycss-webpack` repo and made some changes here: [`HapLifeMan/purifycss-extended-webpack`](https://github.com/HapLifeMan/purifycss-extended-webpack), try it and tell me if that's good for you :)
